export class IpcWindowOptions {
  static DESTROY = 'destroy'
  static SHOW = 'show'
  static HIDE = 'hide'
  static FOCUS = 'focus'
  static BLUR = 'blur'
  static MAXIMIZE = 'maximize'
  static UNMAXIMIZE = 'unmaximize'
  static MINIMIZE = 'minimize'
  static RESTORE = 'restore'
  static RELOAD = 'reload'
  static SET_FULL_SCREEN = 'setFullScreen'
  static SET_TITLE = 'setTitle'
  static FLASH_FRAME = 'flashFrame'
}
